#+title: The Balance Sheet Identity
#+author: Matt Brigida, Ph.D.
#+SETUPFILE: https://fniessen.github.io/org-html-themes/org/theme-readtheorg.setup



*  How Do We Buy Assets?

You issue financial assets (stocks and bonds) to get the money to buy real assets.  These financial assets then have a claim on the assets, as well as the cash flows generated by those assets.  

-  The type of financial assets determines the nature (risk/return) of the claim. 

-  Bond and stock valuation deals with the claim on the cash flows.  Here we'll discuss the claim on the underlying assets themselves.   

* The Balance Sheet Identity

The balance sheet identity: 

$A \equiv L + SE$

where *A* denotes assets, *L* liabilities, and *SE* stockholders' equity. You read this identity as "assets are defined to be liabilities plus stockholders' equity."

-  This is a result of equity being a *residual claim* on the assets/cash flows of the firm.  Equity receives whatever is left over. 

-  So the "identity" is saying all the firm's assets are claimed by someone---debtholders first, and then equityholders get everything else. 



* The Difference Between Identities and Equations

We call the Balance Sheet relationship an *identity* rather than an *equation* because it always holds (because equity just gets whatever is left over).

- Conversely, an equation only holds for certain values.  For example, consider the equation $x^2 - 1 = 0$.  This is only true for $x = \pm 1$

- $A \equiv L + SE$ is always true because $SE$ is simply defined as $A - L$.



* Interactive App

The following interactive app graphically shows the balance sheet identity. The original asset value is $100, and you can set the proportion of those assets financed by debt.  For example, if you set it equal to 0.55, then $55 of the assets was financed via debt.  You can then set the new value of assets. 

- If the new value of assets increases above $100 all the value goes to equityholders, and if the value of assets drops below $100 equityholders absorb the losses (with no debt value lost). 

- If the new value of assets drops below the value of debt, then debtholders incur losses, and the value of equity is negative.

-  Note that this is an accounting relationship---because of *limited liability* equity can never have a negative value.

#+BEGIN_EXPORT HTML
<iframe width="760" height="515" src="https://micfm.shinyapps.io/balance_sheet_identity_app1/"></iframe>
#+END_EXPORT
